flask_app/movies/routes.py
import base64, io, os
from flask import Blueprint, render_template, url_for, redirect, request, flash, jsonify
from flask import current_app as app
from flask_login import login_required, current_user
from flask_mail import Mail, Message
from ..forms import RegistrationForm, LoginForm, SnippetUploadForm, ShareSnippetForm, SearchForm, SnippetReviewForm
from ..models import User, CodeSnippet, load_user, Review, Snippet
from ..utils import current_time

snippets = Blueprint("snippets", __name__)

def get_b64_img(username):
    user = User.objects(username=username).first()
    bytes_im = io.BytesIO(user.profile_pic.read())
    image = base64.b64encode(bytes_im.getvalue()).decode()
    return image

@snippets.route('/', methods=['GET', 'POST'])
def index():
    form = SearchForm()

    language_data = CodeSnippet.objects.aggregate([
        {"$group": {"_id": "$language", "count": {"$sum": 1}}},
        {"$sort": {"count": -1}}
    ])
    languages_with_counts = {data['_id']: data['count'] for data in language_data if data['_id']}
    form.language.choices = [(lang, f"{lang} ({count})") for lang, count in languages_with_counts.items()]

    form.language.choices.insert(0, ("None", "None"))

    snippets = []
    if form.validate_on_submit():
        query = {}
        
        if form.title.data.strip():
            query['title'] = {'$regex': form.title.data.strip(), '$options': 'i'}
        if form.tag.data.strip():
            query['tags'] = {'$in': [tag.strip().lower() for tag in form.tag.data.split(',')]}
        if form.language.data.strip() and form.language.data.strip() != "None":
            query['language'] = form.language.data.strip()
        if form.difficulty.data.strip() and form.difficulty.data.strip() != "None":
            query['difficulty'] = form.difficulty.data.strip()
        snippets = CodeSnippet.objects(__raw__=query)
    else:
        snippets = CodeSnippet.objects.all()

    return render_template('index.html', form=form, snippets=snippets)

@snippets.route("/upload", methods=["GET", "POST"])
@login_required
def upload_snippet():
    form = SnippetUploadForm()
    if form.validate_on_submit():
        newList = form.tags.data.split(",")
        for i in range(len(newList)):
            newList[i] = newList[i].lower()
        snippet = CodeSnippet(
            author=current_user._get_current_object(),
            title=form.title.data,
            code=form.code.data,
            language=form.language.data,
            tags=newList,
            difficulty=form.difficulty.data
        )
        snippet.save()
        share_form = ShareSnippetForm()
        form2 = SnippetReviewForm()
        return render_template("snippet_display.html", share_form=share_form, form=form2, snippet=snippet)

    for f, err in form.errors.items():
        for e in err:
            flash(f"Error: {f} {e}")
    return render_template("upload_snippet.html", form=form)

@snippets.route("/snippet/<snippet_id>", methods=["GET", "POST"])
def snippet_detail(snippet_id):
    snippet = CodeSnippet.objects(id=snippet_id).first()
    if not snippet:
        return redirect(url_for('snippets.index')) 

    form = SnippetReviewForm()
    share_form = ShareSnippetForm()
    if form.validate_on_submit():
        review = Review(
            commenter=current_user._get_current_object(),
            content=form.text.data,
            date=current_time(),
            snippet_id=snippet_id,
            snippet_title=snippet.title,
        )
        review.save()
        return redirect(request.path)

    review_objects = Review.objects(snippet_id=snippet_id)
    reviews = [{'commenter': review.commenter.username,
                'content': review.content,
                'date': review.date,
                'image': get_b64_img(review.commenter.username)
            } for review in review_objects]

    return render_template( "snippet_display.html", form=form, share_form=share_form, snippet=snippet, reviews=reviews)

@snippets.route("/user/<username>")
def user_detail(username):
    user = User.objects(username=username).first()
    if not user:
        return render_template('user_detail.html', error=f'User {username} does not exist')
    reviews = Review.objects(commenter=user)
    image = get_b64_img(username)
    return render_template('user_detail.html', username=username, reviews=reviews, image=image)

@snippets.route('/like-snippet/<string:snippet_id>', methods=['POST'])
@login_required
def like_snippet(snippet_id):
    snippet = CodeSnippet.objects(id=snippet_id).first()
    username = current_user.username
    if username in snippet.likes:
        snippet.likes.remove(username)
    else:
        if username in snippet.dislikes:
            snippet.dislikes.remove(username)
        snippet.likes.append(username)

    snippet.save()

    if not snippet.likes:
        snippet.update(set__likes=[])

    return jsonify({'likes': len(snippet.likes), 'dislikes': len(snippet.dislikes)})

@snippets.route('/dislike-snippet/<string:snippet_id>', methods=['POST'])
@login_required
def dislike_snippet(snippet_id):
    snippet = CodeSnippet.objects(id=snippet_id).first()
    username = current_user.username
    if username in snippet.dislikes:
        snippet.dislikes.remove(username)
    else:
        if username in snippet.likes:
            snippet.likes.remove(username)
        snippet.dislikes.append(username)

    snippet.save()

    if not snippet.dislikes:
        snippet.update(set__dislikes=[])
    return jsonify({'likes': len(snippet.likes), 'dislikes': len(snippet.dislikes)})

@snippets.route('/send-email/<string:snippet_id>', methods=['POST'])
@login_required
def send_email(snippet_id):
    mail = Mail(app)

    snippet = CodeSnippet.objects(id=snippet_id).first()
    share_form = ShareSnippetForm()
    if share_form.validate_on_submit():
        recipient_email = request.form['email']
        msg = Message('You received a new Code Snippet!',
                      sender=app.config['MAIL_USERNAME'],
                      recipients=[recipient_email])
        msg.body = f"Here's a code snippet titled {snippet.title}:\n\n{snippet.code}"
        mail.send(msg)
        flash(f'The snippet has been sent to {recipient_email}!')
        return redirect(url_for('snippets.snippet_detail', snippet_id=snippet_id))
    return render_template("snippet_display.html", snippet=snippet, form=share_form)

@snippets.route('/save-snippet/<string:snippet_id>', methods=['GET', 'POST'])
@login_required
def save_snippet(snippet_id):
    snippet = CodeSnippet.objects(id=snippet_id).first()
    if snippet:
        existing_snippet = Snippet.objects(user=current_user._get_current_object(), snippet=snippet).first()
        if not existing_snippet:
            saved_snippet = Snippet(user=current_user._get_current_object(), snippet=snippet)
            saved_snippet.save()
            flash('Snippet saved successfully!')
        else:
            flash('You have already saved this snippet.')
    return redirect(url_for('snippets.snippet_detail', snippet_id=snippet_id))

@snippets.route('/my-snippets', methods=['GET'])
@login_required
def my_snippets():
    saved_snippets = Snippet.objects(user=current_user._get_current_object())
    return render_template('my_snippets.html', snippets=saved_snippets)

flask_app/users/routes.py
from flask import Blueprint, redirect, url_for, render_template, flash, request
from flask_login import current_user, login_required, login_user, logout_user
import base64, os
from io import BytesIO
from .. import bcrypt
from werkzeug.utils import secure_filename
from ..forms import RegistrationForm, LoginForm, UpdateUsernameForm, UpdateProfilePicForm
from ..models import User
import io, base64

users = Blueprint("users", __name__)

""" ************ User Management views ************ """

@users.route("/register", methods=["GET", "POST"])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('users.account'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        user.save()
        flash('Your account has been created. You may now login')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)

@users.route("/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for("snippets.index"))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.objects(username=form.username.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user)
            return redirect(url_for("users.account"))
        flash('Login Unsuccessful. Please check username and password')
    return render_template('login.html', title='Login', form=form)

@users.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for('snippets.index'))

@users.route("/account", methods=["GET", "POST"])
@login_required
def account():
    update_username_form = UpdateUsernameForm()
    update_profile_pic_form = UpdateProfilePicForm()
    if request.method == "POST":
        if update_username_form.submit_username.data and update_username_form.validate():
            update_username_form.validate_username(update_username_form.username)
            current_user.modify(username=update_username_form.username.data)
            current_user.save()
            flash('Your username has been updated.')
            return redirect(url_for('users.account'))

        if update_profile_pic_form.submit_picture.data and update_profile_pic_form.validate():
            image = update_profile_pic_form.picture.data
            secure_filename(image.filename)
            current_user.profile_pic.replace(image.stream, content_type='images/png')
            current_user.save()
            return redirect(url_for('users.account'))

    def get_b64_img(username):
        user = User.objects(username=username).first()
        bytes_im = io.BytesIO(user.profile_pic.read())
        image = base64.b64encode(bytes_im.getvalue()).decode()
        return image
    img = get_b64_img(current_user.username)
    return render_template("account.html", title="Account", update_username_form=update_username_form, update_profile_pic_form=update_profile_pic_form, image=img)

flask_app/templates/account.html
{% extends "header.html" %}
{% block content %}
<style>
    .link-button {
        display: inline-block;
        background-color: #333;
        color: white;
        padding: 10px 20px;
        text-align: center;
        border-radius: 8px;
        text-decoration: none;
        transition: background-color 0.3s;
        margin-bottom: 1rem;
    }

    .link-button:hover {
        background-color: #555;
    }
</style>

<div class="container mx-auto w-full md:w-2/3 lg:w-1/3" style="text-align: center;">
    {% if image %}
        <img class="rounded-2xl h-24 w-24 mx-auto" src="data:image/png;base64,{{image}}" alt="image" style="display: block;">
    {% endif %}
    <h1>Welcome, {{ current_user.username }}!</h1>
    <br>
</div>

<div class="container mx-auto w-full md:w-2/3 lg:w-1/3">
    <h3 class="text-xl" style="text-align: center;">
        Update Username
    </h3>
    <form class="review-form" method="POST" action="">
        {{ update_username_form.csrf_token }}
        <div class="form-group">
            {{ update_username_form.username.label }}
            {{ update_username_form.username(class="form-content") }}
            {% if update_username_form.username.errors %}
            <div class="alert alert-warning" role="alert">
                {% for error in update_username_form.username.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% endif %}
        </div>
        {{ update_username_form.submit_username(class="review-button") }}
    </form>
</div>

<div class="container mx-auto w-full md:w-2/3 lg:w-1/3">
    <h3 class="text-xl" style="text-align: center;">
        Update Profile Picture
    </h3>
    <form class="review-form" method="POST" action="" enctype="multipart/form-data">
        {{ update_profile_pic_form.csrf_token }}
        <div class="form-group">
            {{ update_profile_pic_form.picture.label }}
            {{ update_profile_pic_form.picture(class="form-content") }}
            {% if update_profile_pic_form.picture.errors %}
            <div class="alert alert-warning" role="alert">
                {% for error in update_profile_pic_form.picture.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% endif %}
        </div>
        {{ update_profile_pic_form.submit_picture(class="review-button") }}
    </form>
</div>

<div class="flex justify-center">
    <a href="{{ url_for('snippets.user_detail', username=current_user.username) }}" class="link-button">View All My Reviews</a>
</div>
<div class="flex justify-center">
    <a href="{{ url_for('snippets.my_snippets') }}" class="link-button">View All My Saved Snippets</a>
</div>

<div style="margin-bottom: 5%"></div>
{% endblock %}

flask_app/templates/base.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link
      rel="stylesheet"
      href="{{url_for('static',filename='compiled.css')}}"
    />
    {% if title %}
        <title>{{ title }}</title>
    {% else %}
        <title>Snippet Reviews</title>
    {% endif %}
</head>
<body>
    {% block header %}
    <h1>Overrideable Content</h1>
    {% endblock %}
</body>
</html>

flask_app/templates/header.html
{% extends "base.html" %} {% block header %}
<div style="display: flex; justify-content: flex-end;">
    <a class="m-5 navlink" href="{{ url_for('snippets.index') }}">
        <span class="hidden sm:block">search-snippet</span>
        <span class="block sm:hidden">Home</span>
    </a>
    {% if current_user.is_authenticated %}
    <div style="display: flex; justify-content: flex-end;">
        <a class="my-5 mr-5 ml-0 navlink" href="{{ url_for('snippets.upload_snippet') }}">Upload-Snippets</a>
        <a class="my-5 mr-5 ml-0 navlink" href="{{ url_for('users.account') }}">Account</a>
        <a class="my-5 mr-5 ml-0 navlink !bg-red-400/20 hover:!bg-red-500/50 !text-red-400 hover:!text-red-300" href="{{ url_for('users.logout') }}">Logout</a>
    </div>
    {% else %}
    <div style="display: flex; justify-content: flex-end;">
        <a class="my-5 mr-5 ml-0 navlink" href="{{ url_for('users.login') }}">Login</a>
        <a class="my-5 mr-5 ml-0 navlink" href="{{ url_for('users.register') }}">Register</a>
    </div>
    {% endif %}
</div>
{% block content %}{% endblock %}{% endblock %}

flask_app/templates/index.html
{% extends "header.html" %}
{% block content %}
<style>
  .container {
    min-height: 85vh;
    margin: 0 auto;
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    width: 80%;
  }

  .form-group {
    margin-bottom: 20px;
    width: 100%;
  }

  .form-control {
    width: 100%;
    padding: 8px;
    border: 1px solid #ccc;
    border-radius: 4px;
  }

  .btn-primary {
    width: 100%;
    padding: 10px;
    background-color: #292929;
    border-radius: 4px;
    color: white;
    cursor: pointer;
    border: 1px solid white;
    transition: background-color 0.3s ease; 
  }

  .btn-primary:hover {
    background-color: #333;
  }

  h2 {
    text-align: center;
    font-size: 1.3rem;
    margin-left: auto;
    margin-right: auto;
    text-decoration: underline;
  }

  ul {
    width: 25%;
  }

  li {
    background-color: #292929;
    margin: 10px 0;
    padding: 10px;
    border: 1px solid white;
    border-radius: 8px;
    transition: background-color 0.3s ease; 
  }

  li a {
    color: #ddd;
    text-decoration: none;
    display: block; 
  }

  li:hover {
    background-color: #333; 
  }

  li a:hover, .btn-primary:hover {
    text-decoration: underline;
  }

</style>
<div class="container">
  <h2>Search a snippet!</h2>
  <form action="{{ url_for('snippets.index') }}" method="post" class="form-horizontal">
    {{ form.csrf_token }}

    <div class="form-group">
      {{ form.title.label(class="control-label") }}
      {{ form.title(class="form-control", placeholder="Enter snippet title") }}
    </div>
    
    <div class="form-group">
      {{ form.tag.label(class="control-label") }}
      {{ form.tag(class="form-control", placeholder="Enter a tag") }}
    </div>

    <div class="form-group">
      {{ form.language.label(class="control-label") }}
      {{ form.language(class="form-control") }}
    </div>

    <div class="form-group">
      {{ form.difficulty.label(class="control-label") }}
      {{ form.difficulty(class="form-control") }}
    </div>

    <div class="form-group">
      {{ form.submit(class="btn btn-primary") }}
    </div>
  </form>
  {% if snippets %}
    <ul style="text-align: center">
      {% for snippet in snippets %}
      <li><a href="{{ url_for('snippets.snippet_detail', snippet_id=snippet.id) }}">{{ snippet.title }} - {{ snippet.language }} - {{ snippet.difficulty }}</a></li>
      {% endfor %}
    </ul>
  {% endif %}
</div>
<div style="margin-bottom: 5%"></div>
{% endblock %}

flask_app/templates/login.html
{% extends "header.html" %}
{% block content %}
<div class="container mx-auto w-full md:w-2/3 lg:w-1/3">
    <h2 class="text-2xl font-bold text-center">Log In</h2>
</div>
<div class="container mx-auto w-full md:w-2/3 lg:w-1/3 text-center my-2">
    If you don't have an account, <a class="text-blue-400 duration-150 hover:text-blue-200 underline" href="{{ url_for('users.register') }}">register here</a>.
</div>
<div class="container mx-auto w-full md:w-2/3 lg:w-1/3">

    {# show flashed messages if an authentication error occurs #}
    {% with messages = get_flashed_messages() %}
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-warning" role="alert">
                    <span>{{ message }}</span>
                </div>
            {% endfor %}
        {% endif %}
    {% endwith %}

    <form class="review-form" method="POST" action="">
        {{ form.csrf_token }}
        <div class="form-group review-input">
            {{ form.username.label }}
            {{ form.username(class="form-content") }}
            {% if form.username.errors %}
            <div class="alert alert-warning" role="alert">
                {% for error in form.username.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% endif %}
        </div>
        <div class="form-group review-input">
            {{ form.password.label }}
            {{ form.password(class="form-content") }}
            {% if form.password.errors %}
            <div class="alert alert-warning" role="alert">
                {% for error in form.password.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% endif %}
        </div>
        {{ form.submit(class="review-button") }}
    </form>

</div>
{% endblock %}

flask_app/templates/my_snippets.html
{% extends "header.html" %}
{% block content %}
<style>
  .container {
    min-height: 60vh;
    margin: 0 auto;
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
  }

  h2 {
    font-size: 1.2rem;
    padding: 0.7rem;
    border-radius: 1rem;
    margin-bottom: 0.5rem;
    background-color: #292929;
    transition: background-color 0.3s ease;
  }

  li {
    background-color: #292929;
    margin: 10px 0;
    padding: 10px;
    border: 1px solid white;
    border-radius: 8px;
    transition: background-color 0.3s ease;
  }

  li:hover, h2:hover {
    background-color: #333;
  }

  li a:hover, h2 {
    text-decoration: underline;
  }
</style>

<div class="container">
    <h2>My Saved Snippets</h2>
    {% if snippets %}
    <ul style="width: 10%; text-align: center;">
        {% for saved_snippet in snippets %}
        <div>
            <li><a href="{{ url_for('snippets.snippet_detail', snippet_id=saved_snippet.snippet.id) }}">{{ saved_snippet.snippet.title }}</a></li>
        </div>
        {% endfor %}
    </ul>
    {% else %}
    <p>No snippets saved yet!</p>
    {% endif %}
</div>
{% endblock %}

flask_app/templates/query.html
{% extends "header.html" %} {% block content %}

{% if error_msg %}
  <b class="text-red-400">
    {{ error_msg }}
  </b>
{% endif %}

<div class="results-container">
  <div class="decoration-container"><div class="decoration"></div></div>
  {% for result in results %}
  <a 
    href="{{ url_for('snippets.movie_detail', snippet_id=result.imdb_id) }}"
    class="group movie-card"
  >
    <img src="{{ result.poster_url }}" class="movie-card-img" alt="missing" />
    <h5 class="movie-card-content"> {{ result.title }}
      <span class="text-neutral-400 font-normal"> &middot; {{ result.year }} </span>
    </h5>
  </a>
  {% endfor %}
</div>

{% endblock %}

flask_app/templates/register.html
{% extends "header.html" %}
{% block content %}
<div class="container mx-auto w-full md:w-2/3 lg:w-1/3">
    <h2 class="text-2xl font-bold text-center">Registration</h2>
</div>
<div class="container mx-auto w-full md:w-2/3 lg:w-1/3 text-center my-2">
    If you already have an account, <a class="text-blue-400 duration-150 hover:text-blue-200 underline" href="{{ url_for('users.login') }}">login here</a>.
</div>

<div class="container mx-auto w-full md:w-2/3 lg:w-1/3">
    <form class="review-form" method="POST" action="">
        {{ form.csrf_token }}
        <div class="form-group review-input">
            {{ form.username.label }}
            {{ form.username(class="form-content") }}
            {% if form.username.errors %}
            <div class="alert alert-warning" role="alert">
                {% for error in form.username.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% endif %}
        </div>
        <div class="form-group review-input">
            {{ form.email.label }}
            {{ form.email(class="form-content") }}
            {% if form.email.errors %}
            <div class="alert alert-warning" role="alert">
                {% for error in form.email.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% endif %}
        </div>
        <div class="form-group review-input">
            {{ form.password.label }}
            {{ form.password(class="form-content") }}
            {% if form.password.errors %}
            <div class="alert alert-warning" role="alert">
                {% for error in form.password.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% endif %}
        </div>
        <div class="form-group review-input">
            {{ form.confirm_password.label }}
            {{ form.confirm_password(class="form-content") }}
            {% if form.confirm_password.errors %}
            <div class="alert alert-warning" role="alert">
                {% for error in form.confirm_password.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% endif %}
        </div>
        {{ form.submit(class="review-button") }}
    </form>
</div>

{% endblock %}

flask_app/templates/snippet_display.html
{% extends "header.html" %}
{% block content %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Upload Your Code Snippet</title>
    <link href="https://cdn.jsdelivr.net/npm/prismjs/themes/prism-tomorrow.css" rel="stylesheet">

    <style>
        .snippet-container {
            margin-left: 25rem;
            margin-right: 25rem;
            margin-top: 5rem;
            margin-bottom: 10rem;
            padding: 20px;
            border: 1px solid #ccc;
            border-radius: 8px;
        }
        
        .snippet-container h1 {
            color: #333;
        }

        .snippet-container pre {
            background-color: #292929;
            border: 1px solid #eee;
            padding: 10px;
            overflow: auto; 
            max-width: 100%;
            box-sizing: border-box;
        }

        .snippet-container code {
            display: inline; 
            white-space: pre;
        }

        #tag-style {
            background-color: black;
            display: inline-block;
            margin-right: 0.5rem; 
            border: 1px solid white;
            border-radius: 0.25rem;
            padding: 0.25rem;
        }

        .btn {
            background-color:#333;
            border-color:#eee;
            border: 1rem;
            border-radius: 0.5rem;
            padding: 0.75rem;
            margin: 0.5rem 0.5rem 0.0rem 0.0rem;
        }

        .btn:hover {
            background-color: #555;
        }

    </style>        
</head>
<div class="snippet-container">
    <h1 style="font-size: 3rem; text-decoration: underline">{{ snippet.title }}</h1>
    <p><strong>Language:</strong> {{ snippet.language }}</p>
    <p><strong>Difficulty:</strong> {{ snippet.difficulty }}</p>
    <h3>Code:</h3>
    <pre><code class="language-{{ 'cpp' if snippet.language.lower() == 'c++' else snippet.language.lower() }}">{{ snippet.code }}</code></pre>
    <p>Uploaded by: <b>{{ snippet.author.username }}</b></p>
    <h2 style="font-size: 2rem;">Tags:</h2>
    {% for tag in snippet.tags %}
        <span id="tag-style">{{ tag }}</span>
    {% endfor %}

    <div class="button-container">
        <button type="button" class="btn" onclick="likeSnippet('{{snippet.id}}')">Likes:
            <span id="likes-count" style="text-decoration: underline;">{{ snippet.likes | length }}</span>
        </button>
        <button type="button" class="btn" onclick="dislikeSnippet('{{snippet.id}}')">Dislikes:
            <span id="dislikes-count" style="text-decoration: underline;">{{ snippet.dislikes | length }}</span>
        </button>
    </div>

    {% if current_user.is_authenticated %}
    <div class="button-container">
        <button type="button" class="btn btn-primary" onclick="saveSnip()">Save Code Snippet</button>
    </div>
    <div class="button-container">
        <form method="POST" action="{{ url_for('snippets.send_email', snippet_id=snippet.id) }}">
            {{ share_form.csrf_token }}
            <input type="email" name="email" required placeholder="Enter recipient email" class="form-content" style="width: 25rem;">
            <button type="submit" class="btn btn-primary">Share via Email</button>
        </form>
        {% for mesg in get_flashed_messages() %}
            <h2><em>{{ mesg }}</em></h2>
        {% endfor %}
    </div>
    <div>
        <div class="container mx-auto">
          <form method="POST" action="" class="review-form">
            {{ form.csrf_token }}
            <div class="form-group review-input">
              {{ form.text.label }} {{ form.text(class="form-content") }}
              {% if form.text.errors %}
                <div class="alert alert-warning" role="alert">
                  {% for error in form.text.errors %}
                  <span>{{ error }}</span>
                  {% endfor %}
                </div>
              {% endif %}
            </div>
            {{ form.submit(class="review-button") }}
          </form>
        </div>
    </div>
    {% endif %}

    <div>
        <h1 class="reviews-title"> Reviews
            <small class="reviews-count"> {{ reviews | length }} reviews </small>
          </h1>
          <ul class="review-container">
            {% for review in reviews %}
              <li class="review flex gap-2">
                <img class="h-20 w-20 rounded-lg" src="data:image/png;base64,{{review.image}}" alt="" />
                <div class="w-full">
                  <span class="review-date">{{ review.date }}</span>
                  <a class="review-commenter" href="{{ url_for('snippets.user_detail', username=review.commenter) }}">
                    @{{ review.commenter }}
                  </a>
                  <p class="review-content">{{ review.content }}</p>
                </div>
              </li>
            {% endfor %}
          </ul>
    </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/prismjs/prism.js"></script>
<script src="https://cdn.jsdelivr.net/npm/prismjs/components/prism-{{ 'cpp' if snippet.language.lower() == 'c++' else snippet.language.lower() }}.min.js"></script>
<script>
    function saveSnip() {
        window.location.href = `/save-snippet/{{ snippet.id }}`;
    }

    function likeSnippet(snippetId) {
        fetch(`/like-snippet/${snippetId}`, { method: 'POST' })
        .then(response => response.json())
        .then(data => {
            document.getElementById('likes-count').textContent = data.likes;
            document.getElementById('dislikes-count').textContent = data.dislikes;
        })
        .catch(error => console.error('Error:', error));
    }

    function dislikeSnippet(snippetId) {
        fetch(`/dislike-snippet/${snippetId}`, { method: 'POST' })
        .then(response => response.json())
        .then(data => {
            document.getElementById('likes-count').textContent = data.likes;
            document.getElementById('dislikes-count').textContent = data.dislikes;
        })
        .catch(error => console.error('Error:', error));
    }
</script>
{% endblock %}

flask_app/templates/user_detail.html
{% extends "header.html" %} {% block content %}
{% if error %}
    <b class="text-red-400" role="alert">
        {{ error }}
    </b>
{% endif %}
<div class="container mx-auto w-full md:w-2/3 lg:w-1/3">
    <img class="rounded-2xl" src="data:image/png;base64,{{image}}" alt="image">
    <h1>{{ username }}'s Reviews</h1>
    <br>
    <p>Number of Reviews: {{ reviews|length }}</p>
</div>
<div class="container mx-auto w-full md:w-2/3 lg:w-1/3">
    {% for r in reviews %}
        <div class="review">
            <p>Date: {{ r.date }}</p>
            <p>Snippet: {{ r.snippet_title }}</p>
            <p>Content: {{ r.content }}</p>
        </div>
        <br>
    {% endfor %}
</div>
{% endblock %}